sudo: requires
services:
  - docker

before_install:
  - docker build -t frozenphantom/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run frozenphantom/react-test npm test -- --coverage

after_success:
  - docker build -t frozenphantom/multi-client  ./client
  - docker build -t frozenphantom/multi-nginx   ./nginx
  - docker build -t frozenphantom/multi-server  ./server
  - docker build -t frozenphantom/multi-worker  ./worker

  # login to Docker CLI, las credenciales se ponen en Travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to Docker
  - docker push frozenphantom/multi-client
  - docker push frozenphantom/multi-nginx
  - docker push frozenphantom/multi-server   
  - docker push frozenphantom/multi-worker

  

